plugins {
    id 'com.android.application'
}

android {
    namespace 'com.salapremios.demo'
    compileSdk 35

    defaultConfig {
        applicationId 'com.salapremios.demo'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1-demo'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
